### ISSUE TITLE
All design elements deleted on first sync

### ISSUE THREAD

**Issue by markleusink** [camac/Swiper#17]
I've experienced a couple of times now that on opening a database that hasn't been opened before (in the current Designer session), the NSF syncs with the ODP and removes all design elements. When all code is committed, that is not a big issue, since I can just revert the changes. 

The problem is that I can't reliably reproduce the error, but it seems to occur only in repositories that contain the ODP for multiple NSF's. Anyone seen this behaviour too?

I'm also not sure if this is a Swiper or Designer issue.

**Comment by ursus-the-bear** [comment]
Mark, I had exactly the same thing happen to me yesterday - at first I thought that I did something wrong but now hearing that you have the same issue... I pressed the sync button in the Toolbar (I only have 1 button and not 3/4 like in the example text) and had all my elements!

**Comment by camac** [comment]
strange! this happened to me for the first time yesterday as well!
lucky i didn't lose too much. i hope you both didn't either.

my gut feeling is that it wouldn't be swiper that caused it but you never know i will have a look into trying to reproduce

until then commit early and commit often

**Comment by markleusink** [comment]
Some additional info:

- Designer is 901FP8IF1
- Swiper is 2.0.0.201703162255
- Build automatically is OFF
- Automatic export of design elements (NSF to disk) is ON
- Automatic import of design elements (disk to NSF) is OFF

**Comment by ursus-the-bear** [comment]
same as mark here except I have build automatically ON - yes, I know, n00b :o)

**Comment by camac** [comment]
Thanks for the additional info.
So I understand for Mark, it happened on opening the application e.g. in the designer list of projects
and for Ursus: it happening after clicking the 'sync' toolbar button? 

Mark what do you mean ODP for multiple NSFs? I only ever have 1 ODP for 1 NSF

Ursus I use build automatically ON too :)

**Comment by markleusink** [comment]
Yes: when opening the application from the designer list of applications (the 'Applications' view).

And I meant 1 Git repo containing the ODP for a couple of NSF's in subfolders. But most of my projects have that, so not sure if it's relevant.

**Comment by ursus-the-bear** [comment]
Yes, happens when I press the button -> to be clear though, it has only happened to me once so far!

**Comment by marcisbe** [comment]
It happened to me several times. I made some tests and this happens even if I remove swiper from db. In my case it happens with 2 databases. if I click on first db and press "Sync with ODS" swiper toolbar button content of second db are deleted from disk. It doesn't happen if I press right mouse button Team Developement > Sync with ODS.

**Comment by camac** [comment]
Sorry for the delay, I have finally done some testing myself. I found similar to already said above.

I can only repeat the problem by using the sync toolbar button, and syncing 2 different projects, one after the other.
I don't get the problem when using the Team Dev -> Sync with ODS right click menu or the File -> team Dev -> Sync with ODS
also same as marcisbe, I have removed Swiper from the projects and still get the problem. So, I don't think the problem is related to Swiper's metadata filtering. 

My current thinking is that the problem is related to way that the 'Sync Job' is set up when using the toolbar button.

The toolbar button is just calling a sub class of the same 'SyncAction' that is called by the right-click menu, somewhere in the set up it chooses the 'Designer Project' and the 'On Disk Project'
My best guess is that it is getting the association between projects wrong, and then thinks files are deleted from one so deletes it from the other.
My sub-classed SyncAction wasn't using the same constructors as the parent 'SyncAction' which had some 'initOnUIThread' calls, so I fixed that locally but I still get the problem.

I'll need to have a think about it some more but for now I would just avoid using the toolbar buttons. Or only use them when working on a single project

**Comment by ursus-the-bear** [comment]
Thank you for the update - I'll see if that helps :o)

**Comment by markleusink** [comment]
Hard to pinpoint exactly where it fails. I noticed this happening yesterday when opening a database and the related ODP in Designer wasn't open for some reason. It removed all design elements. I then closed the database and re-opened it (causing the ODP to also open). The database then automatically synced with the ODP telling it to remove all design elements, since they weren't in the db anymore.

**Comment by camac** [comment]
Hi All, just thought I would point out that the latest release 2.0.1 has hopefully fixed this one, by blocking the UI when the sync is triggered by the toolbar button. 
This way you cannot select another DB while the sync is occuring

Let me know if you still see this issue after upgrading to 2.0.1

**Comment by markleusink** [comment]
Thanks! I installed the new version already 👍 

Let's close this issue for now. I'll reopen it when the issue reappears.
