### ISSUE TITLE
Strange issue after installing Swiper - not sure if it's Swiper

### ISSUE THREAD

**Issue by markleusink** [camac/Swiper#6]
After installing Swiper I'm seeing a strange issue: 'sometimes' (gotta love that in an issue report...) it will show the Sync Conflict dialog for a .metadata file. If I then click on Compare, it compares the conflicted .metadata file from the on-disk version with the Java class file in the database (not the metadata). Could that be a side effect of Swiper? This database doesn't have Swiper enabled yet.

I'm also seeing much more .metadata files marked as 'modified', but I haven't touched those files (or signed it).

Here's a screenshot:

![screenshot 2015-12-15 12 33 01](https://cloud.githubusercontent.com/assets/1773707/11809563/0a490536-a328-11e5-99b4-d31cc9d1f2e5.png)

**Comment by camac** [comment]
Hi Mark, If the database doesn't have Swiper enabled then I can't think of any way that Swiper would interfere with the normal operation of Designer source control.
The way Swiper works, is that when you enabled Swiper it adds a project nature (called Swiper) to the project, which installs 2 'builders', one that runs before the Designer Source Control Builder, and one that runs afterwards.
It also enables the 'Filter Selected' option in the project right-click menu.

These are the only 2 ways that swiper will get involved with the source control sync.

The Sync Conflict dialog is launched from within the normal Designer Source Control Builder, so whatever logic that it is using to match up 2 files is coming from that builder.

Stranger things have happened though, I will leave this issue open for a little while so that if you find any more evidence I can double check it, because I would hate to see Swiper being the cause of this but if it is I would prefer to fix the issue

**Comment by markleusink** [comment]
I disabled Swiper for a couple of weeks and didn't see the issue anymore. Enabled it yesterday and the issue started appearing again on a database that doesn't have Swiper enabled and that I work on almost daily. Weird...

**Comment by markleusink** [comment]
Closing this for now. If I see it again with Swiper 2, I'll re-create it.
