### ISSUE TITLE
Swiper says it's filtering but I can see it

### ISSUE THREAD

**Issue by xpagedeveloper** [camac/Swiper#8]
If I look at logging it says that it's filtering but I can't see that is has done that.
I've used Dora in this project before and everything worked well, but asfter adding swiper it doesn't filter metadata. I did remove the old Dora stuff from the project before adding swiper.

Any ideas?

```
<record>
    <date>2016-02-17T10:22:59</date>
    <millis>1455700979520</millis>
    <sequence>3217</sequence>
    <level>FINEST</level>
    <class>com.ibm.commons.log.AbstractLogMgr</class>
    <method>log</method>
    <thread>39</thread>
    <message>Swiper: About To FilterPhone24.png.metadata</message>
</record>
<record>
    <date>2016-02-17T10:23:00</date>
    <millis>1455700980540</millis>
    <sequence>3218</sequence>
    <level>INFO</level>
    <class>SwiperUtil</class>
    <method></method>
    <thread>39</thread>
    <message>Swiper: Filtered Phone24.png.metadata</message>
</record>

```

**Comment by camac** [comment]
Hi Fredrik, That is very strange, what happens when you right-click the Phone24.png file in the Lefthand side Domino Project Navigator and then click 'Swiper -> Filter Selected'
Does it filter it then?

**Comment by xpagedeveloper** [comment]
No, nothing. is does work that way either.
I've installed swiper thru an update site could that be a problem ?

**Comment by xpagedeveloper** [comment]
After a restart of the client again and the machine. suddenly it started to work.
How do I get it to filter all files in the project by default ?

**Comment by camac** [comment]
Unfortunately there is no quick way to filter all the files. You will need
to highlight them in left hand side and 'Swiper -> filter Selected'
It is annoying but you should only have to do it once.

Unfortunately Swiper only runs either during a build (for recent updated
files) or when used from the left hand navigator with 'Swiper -> Filter
Selected'
This means it does not run during the initial project sync (when opening a
project) or with 'Team Development -> Sync Project'

In the future, Swiper will be integrated with the Sync process so that it
will be run whenever a sync takes place but this is probably a couple of
months away
