### ISSUE TITLE
Question on .metadata filtering

### ISSUE THREAD

**Issue by markleusink** [camac/Swiper#9]
It appears that .metadata files are filtered randomly by Swiper: sometimes they end up correctly in the ODS as a formatted XML document and sometimes it seems that they're not filtered at all. Can you explain why this happens?

I have automatic import & export enabled and build automatically turned off: if I build the application the files are synced to the ODS. I try not to use the Team Dev > Sync option.

Thx!

**Comment by camac** [comment]
Hi Mark, there are a few things that could be happening.
1. Initial Project Sync - When the project is opened it does an initial
   sync, which does NOT trigger Swiper. Swiper currently will only run during
   a build, this initial sync is not part of a Build. Any files exported at
   this point will not be filtered as Swiper is not involved.
2. Incremental Build - If the file had not been changed since the last
   build, it would not be included in the build, and therefore would not be
   included in the Sync
3. Domino does not export the file - Within the Domino Source Control
   plugin's export process, it does a check to see if the original file is the
   same as the exported file, if so it does not export the file (and therefore
   would not export the metadata file either.

Currently the way the swiper works is:
- It checks which files are included in the 'Build' (for incremental build
  is only the files changed since last build, for full build it is all)
- For each of this files it records the timestamp of the ODP file
- Domino Runs it's Sync processes
- Swiper then checks the ODP files for updated timestamps, if the file has
  changed, it will then filter it

Unfortunately this method does not cover every situation, this is why the
'Filter Selected' option is there.

Thankfully IBM are investigating some changes to allow Swiper to run every
time (not complete yet though)

**Comment by markleusink** [comment]
Thanks for clarifying that. Fingers crosses that IBM will improve the whole sync process in a next release of Domino...
